version: '1.3'

services:
  mqttBroker:
    image: eclipse-mosquitto:2.0.14
    container_name: mqttBroker_container
    restart: always
    ports:
      - '9001:9001'
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    networks:
      livello_bridge:
        ipv4_address: 172.21.0.2
  
  client:
    build: .
    restart: always
    depends_on:
      - mqttBroker
    networks:
      livello_bridge:
        ipv4_address: 172.21.0.3

networks:
  livello_bridge:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/16
         gateway: 172.21.0.1
